### ISSUE TITLE
Negative prompts?

### ISSUE THREAD

**Issue by alastaira** [dangeng/visual_anagrams#13]
Hi! Firstly, many thanks for sharing this project - it's fascinating! :)

I'm trying to understand how/if negative prompts can be added to better guide the generation of each view... but I'm having some issues with my understanding. As far as I can see, the generate.py script generates a list of matching positive _and_ negative prompt embeddings from the supplied command line prompts: 
```
prompts = [f'{args.style} {p}'.strip() for p in args.prompts]
prompt_embeds = [stage_1.encode_prompt(p) for p in prompts]
prompt_embeds, negative_prompt_embeds = zip(*prompt_embeds)
prompt_embeds = torch.cat(prompt_embeds)
negative_prompt_embeds = torch.cat(negative_prompt_embeds)  # These are just null embeds
```
(https://github.com/dangeng/visual_anagrams/blob/491b76b48161afa22eb6303d259eeebe896a54f6/generate.py#L50-L54)

The final comment suggests that the negative prompt embedding is null, but the diffusers library states:
```
negative_prompt_embeds (`torch.Tensor`, *optional*):
  Pre-generated negative text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt
  weighting. If not provided, negative_prompt_embeds will be generated from `negative_prompt` input
  argument.
```
https://github.com/huggingface/diffusers/blob/fdb1baa05c8da5b4ed3e7a62200f406dcb26ba79/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L333C1-L336C26

So... should I be providing negative_prompt input to sample_stage_1 instead? Any advice, or an example of how to add negative prompts would be gratefully appreciated!

**Comment by dangeng** [comment]
Hello, thanks for your interest in our work!

To use negative prompts you can just supply it to `encode_prompt`:

`stage_1.encode_prompt("positive prompt", negative_prompt="negative prompt")`

The modification to our code would probably look something like:

`prompt_embeds = [stage_1.encode_prompt(p, negative_prompt=n) for p, n in zip(prompts, negative_prompts)] `

where `negative_prompts` is a list of your negative prompts. I added the comment `#These are just null embeds` because when no `negative_prompt` argument is given to `encode_prompt`, it just returns null text embeddings for the negative prompt (which is standard for classifier free guidance). We're using DeepFloyd, so the documentation for the `encode_prompt` function can be found [here](https://github.com/huggingface/diffusers/blob/e1df77ee1ec0400195ad8dcb2099d137b34c9b9f/src/diffusers/pipelines/deepfloyd_if/pipeline_if.py#L160), but it's pretty similar to the stable diffusion one you linked.

By the way, we actually played around with negative prompting, and [discuss it in our paper](https://arxiv.org/pdf/2311.17919) in section 4.2. Specifically, we use the other view's prompt at the negative prompt for a given view, and we found it doesn't work that well for reasons discussed in the paper. However, I can see maybe using something generic like "low quality photo" as the negative prompt could help improve things! Please let us know if you find something interesting :)
