### ISSUE TITLE
Code for Figure 7 in the paper

### ISSUE THREAD

**Issue by yaseryacoob** [dangeng/visual_anagrams#15]
Can you please share the code on Random Orthogonal  transformation in Figure 7 in the paper?

Many thanks

**Comment by dangeng** [comment]
Hi Yaser,

Great talking to you at CVPR! Here's some quick and dirty code to get the orthogonal stuff working with SDv1.5

[This code should generate a random orthogonal matrix](https://gist.github.com/dangeng/88ac9ef6dac1ba8c6d0952c3afc35cb7), and save it as `orthogonal_matrix.pth`. It's a bit slow, since it's doing SVD on a 16384x16384 matrix, but it takes about 350 seconds on our lab computer.

Then, running this code:

```python
import torch
from diffusers import DDIMScheduler
from pipeline_rotations import MyStableDiffusionPipeline
from torchvision.utils import save_image


model_id = "stabilityai/stable-diffusion-2-base"

scheduler_ddim = DDIMScheduler.from_config(model_id, subfolder="scheduler", )
pipe = MyStableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler_ddim, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = ["a photo of a rabbit", "a photo of a duck"]
images = pipe(prompt, num_inference_steps=999, num_images_per_prompt=1, output_type='torch').images
save_image(torch.tensor(images).permute(0,3,1,2).float(), 'out.png')
```

with `MyStableDiffusionPipeline` [copied from this gist](https://gist.github.com/dangeng/ae3cf744f51ed73ab9e1bca4e4ebdf36) should give you samples. You will need to change line 131 of the definition of `MyStableDiffusionPipeline` with the path of the random orthogonal matrix generated above.

Please let me know if you run into any problems, as I haven't touched this code in ~8 months and it's also quite hacky. 

Best,
Daniel
