### ISSUE TITLE
Optimal parameters?

### ISSUE THREAD

**Issue by tripathiarpan20** [dangeng/visual_anagrams#2]
Hi!
First of all, thanks for open-sourcing this amazing work!

I am currently trying the Colab notebook and the results obtained so far don't match the fidelty of the results on the X announcement thread, any tips/tweaks to get the same quality of results?

![image](https://github.com/dangeng/visual_anagrams/assets/42506819/7614a039-d28d-415e-b91f-335dec50e917)

**Comment by dangeng** [comment]
Hi, thanks for your interest!

We found that choosing the prompts was pretty crucial to making good illusions. I think for a lot of prompt pairs, it might just be impossible to create a good illusion. For example, "photos" of things tended to produce poor illusions, which is what I think is going on here. This is probably because "photos" are much more constraining than, say, "paintings." With photos minute details are important to get right, but with "paintings" the model has more liberty. This makes it much easier to reuse elements of one view for another. For example, a brush stroke may resemble "an eye" from one view, but "a mouth" in another. Whereas in a photo, "an eye" will probably never look like "a mouth" no matter how you orient it.

Also, the illusions on the website were the best ones that we generated. You can check out our paper for random samples. They look a bit worse, but if you choose your prompts carefully they are pretty decent.

We have some tips for choosing prompts in the [readme](https://github.com/dangeng/visual_anagrams/blob/main/readme.md), which I've added to the colab notebook. Thanks for pointing this out!

**Comment by inbumpark** [comment]
Hi! I'd also like to add that using reduction as 'mean' instead of 'alternate' would provide better results, as can be shown in the paper too.
