### ISSUE TITLE
Deepfloyd alternative?

### ISSUE THREAD

**Issue by malik0** [dangeng/visual_anagrams#9]
Hi, 
Is there an alternative we can use instead of DeepFloyd? thanks

**Comment by dangeng** [comment]
Hey! The method requires a pixel diffusion model, and I'm unfortunately not aware of any other very very good pixel diffusion models that are public. There's Imagen, but it's not public. You could also try using Stable Diffusion, which [this colab notebook](https://github.com/tancik/Illusion-Diffusion) does, but I think the quality will be a bit worse because it's doing diffusion in latent space (see the paper for details). If you are aware of any really really good public pixel-diffusion models, I would love to know!
